name: Code quality checks
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  qa:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: composer
        uses: docker://composer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: install --no-interaction --prefer-dist --optimize-autoloader

      - name: phive
        uses: './.github/actions/phive-ant'
        with:
          args: 'getphive'

      - name: phive install
        uses: './.github/actions/phive-ant'
        env:
          phive.bin: "/phive.phar"
        with:
          args: -Dphive.bin=./phive.phar install-tools

      - name: php-cs-fixer
        uses: './.github/actions/phive-ant'
        env:
          phive.bin: "/phive.phar"
        with:
          args: -Dphive.bin=./phive.phar php-cs-fixer

